In [4]:

from faker import Faker
import csv
output=open('/home/csv_data/data.csv','w')
fake=Faker()
header=['name','age','street','city','state','zip','lng','lat']
mywriter=csv.writer(output)
mywriter.writerow(header)
for r in range(100):
    row =[fake.name(),fake.random_int(min=18,max=80, step=1), 
                       fake.street_address(), fake.city(),fake.state(),
                       fake.zipcode(),fake.longitude(),fake.latitude()]
    print(row)
    mywriter.writerow(row)

output.close()

['Erik Brown', 69, '35314 Richard Pike', 'Stuartfort', 'New York', '11259', Decimal('-101.961450'), Decimal('28.990668')]
['Rhonda Davis', 60, '7815 Silva Course Suite 850', 'West Kimberly', 'Virginia', '94630', Decimal('36.347566'), Decimal('-77.8410125')]
['Ashley Sweeney', 65, '359 Galvan Junctions', 'Garciaburgh', 'Kentucky', '95218', Decimal('-147.560522'), Decimal('26.5141375')]
['Mary Taylor', 70, '70898 Lopez Corner Apt. 689', 'North Donnafort', 'Michigan', '22589', Decimal('-130.562621'), Decimal('85.1859815')]
['Jason Collier PhD', 36, '50311 Alexander Gateway', 'Lake Shannon', 'Nevada', '99949', Decimal('30.573417'), Decimal('-48.122253')]
['Emily Roberts', 57, '59650 Fowler Branch Suite 041', 'South David', 'Kentucky', '06338', Decimal('93.053057'), Decimal('-27.1157525')]
['Marisa Peters', 69, '572 Potter Common Suite 637', 'Franklinberg', 'Florida', '96755', Decimal('114.301382'), Decimal('-3.5733305')]
['Alex Nelson', 26, '69317 Walker Burgs', 'Leeborough', 'Hawaii', '19796', Decimal('-158.897402'), Decimal('-36.336378')]
['Andrew Landry', 69, '5990 Tammy Junction', 'Port Jasonburgh', 'Massachusetts', '73915', Decimal('-96.677418'), Decimal('-41.869736')]
['Joseph Smith', 18, '20077 Susan Port', 'West Tiffanymouth', 'Arkansas', '59028', Decimal('-71.660352'), Decimal('56.0499055')]
['Nicole Johnson', 56, '672 Johnson Terrace', 'Gabrielmouth', 'South Carolina', '51361', Decimal('-19.416160'), Decimal('38.268995')]
['Adam Perez', 28, '1875 Michelle Way Suite 994', 'Newmanfort', 'Minnesota', '77790', Decimal('57.409422'), Decimal('-74.394384')]
['Jeffery Sosa', 31, '691 Cochran Route', 'Howellborough', 'Nevada', '29262', Decimal('144.044720'), Decimal('-5.1880265')]
['Lindsey Jordan', 67, '31069 Brandon Mill Apt. 945', 'South Veronicatown', 'Virginia', '16732', Decimal('152.464124'), Decimal('-30.8222685')]
['Caleb Young', 34, '3339 Gregory Way Apt. 157', 'Timothyfurt', 'Arkansas', '01178', Decimal('-117.812746'), Decimal('-43.5806815')]
['Cindy Horton', 54, '088 Ryan Roads Apt. 351', 'Hernandezstad', 'Alabama', '60222', Decimal('-50.808363'), Decimal('38.2134975')]
['Olivia Stevenson', 32, '086 Adkins Coves', 'Lake Brandonmouth', 'Oklahoma', '60782', Decimal('49.393541'), Decimal('-37.603083')]
['Darrell Hunt', 62, '59704 Allison Vista', 'Austinville', 'West Virginia', '53552', Decimal('10.495347'), Decimal('65.2539075')]
['Timothy Rhodes', 23, '1259 Mark Pike', 'Silvaport', 'Nevada', '30584', Decimal('55.836026'), Decimal('-44.302113')]
['Nicole Gonzales', 27, '0523 Derek Corners Apt. 987', 'Kevinmouth', 'North Dakota', '67492', Decimal('120.457514'), Decimal('-14.8859395')]
['Seth Jordan', 29, '768 Christopher Prairie Suite 425', 'South Nicholasmouth', 'Oregon', '88743', Decimal('90.333175'), Decimal('-58.0881415')]
['Pamela Nunez', 46, '34558 Shaw Lodge', 'South Angelaside', 'New Jersey', '17552', Decimal('-174.623995'), Decimal('-35.4847705')]
['John Taylor', 66, '19598 Holland Stream', 'East Meganland', 'North Dakota', '81701', Decimal('121.014383'), Decimal('-69.6060215')]
['Richard Flores', 28, '9191 Parrish Mountains Apt. 724', 'Elizabethview', 'Ohio', '91748', Decimal('112.526040'), Decimal('-61.291115')]
['Emma Chavez', 52, '87789 Jessica Burg', 'Kevinborough', 'Rhode Island', '83071', Decimal('106.626651'), Decimal('-38.7104595')]
['Michael Aguirre', 50, '25302 Natasha Highway Suite 152', 'New Nichole', 'New Jersey', '82546', Decimal('-129.474683'), Decimal('-58.4489845')]
['Dr. Susan Powell DDS', 42, '23830 Stephanie Locks Suite 160', 'Justinborough', 'Ohio', '83055', Decimal('-162.394091'), Decimal('-81.1989715')]
['Zachary White', 70, '536 Miller Plains', 'East Cameron', 'Minnesota', '75853', Decimal('173.100572'), Decimal('4.8977125')]
['Diane Miranda', 54, '17028 Joseph Squares', 'Mcdowellville', 'Massachusetts', '77127', Decimal('17.787275'), Decimal('-23.9136645')]
['Tyler Ramirez', 49, '01572 Young Forges', 'East Margaretville', 'Nebraska', '98330', Decimal('71.991805'), Decimal('-23.947907')]
['Kelly Mullen', 50, '206 Holly Path Suite 357', 'Torreshaven', 'North Dakota', '67574', Decimal('-80.826057'), Decimal('-32.263253')]
['William Goodwin', 32, '642 Werner Crest Suite 012', 'Port Joseph', 'Kansas', '34469', Decimal('-44.131958'), Decimal('16.935323')]
['Dr. Laura Clark', 22, '570 Ward Hill Suite 770', 'New Andrewfort', 'Georgia', '69314', Decimal('50.346109'), Decimal('-32.391925')]
['Stephen Osborne', 71, '5291 Ramos Mills Apt. 762', 'New Adam', 'New Mexico', '78593', Decimal('10.575329'), Decimal('70.3318145')]
['Kathleen Young', 56, '3636 Nicholas Skyway Apt. 336', 'South James', 'Virginia', '82679', Decimal('12.925468'), Decimal('-38.357795')]
['Michael Owens', 36, '261 Justin Estate', 'Port Keithtown', 'Oklahoma', '05972', Decimal('-25.958373'), Decimal('15.440437')]
['Tiffany Morales', 78, '62723 Taylor Drive', 'Angelamouth', 'Colorado', '52437', Decimal('18.828860'), Decimal('61.9617925')]
['Alison Buckley', 69, '68484 Snow Trace Suite 337', 'New Sherry', 'Arkansas', '15851', Decimal('69.935349'), Decimal('36.6823535')]
['Michelle Lopez', 69, '709 Booker Forks Suite 137', 'Phelpsport', 'Maine', '39724', Decimal('-37.542242'), Decimal('-5.5234595')]
['Mallory Lee', 59, '4776 Harper Spring Apt. 917', 'Vincentmouth', 'Maryland', '43892', Decimal('65.616268'), Decimal('87.3931645')]
['Christopher Bonilla', 26, '3385 Wyatt Knolls Apt. 750', 'West Karenside', 'Pennsylvania', '27519', Decimal('125.883914'), Decimal('49.359897')]
['Daniel Lawrence', 32, '91937 Robin Green Apt. 603', 'Collierville', 'New Jersey', '38834', Decimal('-68.835677'), Decimal('55.7068765')]
['Timothy Moore', 33, '658 Alyssa Road Suite 437', 'South Courtneyfort', 'Massachusetts', '58180', Decimal('109.654489'), Decimal('-52.424862')]
['Jose Alexander', 78, '822 Tanya Estates', 'Michelleside', 'Vermont', '06516', Decimal('-69.348839'), Decimal('-57.5618695')]
['Linda Edwards', 28, '544 Jason Forge Apt. 816', 'Port Kimberlybury', 'Nevada', '09151', Decimal('156.214084'), Decimal('88.584568')]
['Steven Rice', 22, '4879 Sweeney Union Apt. 508', 'Port Amandamouth', 'Louisiana', '55736', Decimal('-62.738028'), Decimal('-80.6420015')]
['Seth Brewer', 59, '1528 Mary Burg Suite 353', 'North Stacey', 'Missouri', '37133', Decimal('66.956930'), Decimal('-67.8754775')]
['Julie Smith', 19, '2849 Kerr Ridges Apt. 363', 'North Jamesborough', 'Vermont', '78111', Decimal('-34.311867'), Decimal('-70.1536445')]
['Joel Mcdonald', 48, '36989 Luis Freeway', 'Christinatown', 'Idaho', '64578', Decimal('141.710288'), Decimal('-11.866232')]
['Anthony Davis', 75, '140 Schmitt Square', 'Harrismouth', 'North Dakota', '13846', Decimal('-78.246804'), Decimal('-4.9722825')]
['Heidi Davies', 53, '53278 Rogers Parkway', 'East Larry', 'Kansas', '17586', Decimal('-48.626900'), Decimal('-77.574174')]
['Wendy Rodriguez', 31, '814 Michael Skyway Apt. 369', 'Lake Michellebury', 'Ohio', '43249', Decimal('82.038377'), Decimal('-13.654906')]
['Carlos Cross', 52, '18128 Amy View', 'Davidport', 'Delaware', '79658', Decimal('4.616222'), Decimal('-10.984948')]
['Christopher Cortez', 25, '3400 Williams Trafficway Apt. 631', 'North Shaunstad', 'Tennessee', '17040', Decimal('-128.433878'), Decimal('-22.2930785')]
['Jason Rosales', 42, '74550 Bell Via', 'Christystad', 'Ohio', '48309', Decimal('-17.350216'), Decimal('13.151799')]
['Marc Rodriguez', 18, '9869 Barrera Greens Suite 593', 'Joannabury', 'Kentucky', '15485', Decimal('33.848830'), Decimal('-83.3634875')]
['Robert Myers', 30, '1242 Jackson Alley Suite 413', 'Shieldsfort', 'Florida', '55707', Decimal('-169.568708'), Decimal('-82.4150915')]
['Steven Mahoney', 55, '5291 Mayer Point Suite 577', 'Jennifermouth', 'Colorado', '57743', Decimal('-38.300333'), Decimal('-12.9181425')]
['Ricky Harris', 30, '48066 Trevor Park Suite 309', 'Laurabury', 'South Dakota', '08432', Decimal('155.636582'), Decimal('55.7193785')]
['Sean Taylor', 55, '94682 Allison Mission', 'Lake Katieton', 'Rhode Island', '13506', Decimal('-136.024542'), Decimal('-89.767445')]
['Ryan Snyder', 53, '491 Mary Turnpike Apt. 433', 'North Jamesshire', 'Florida', '10390', Decimal('59.668772'), Decimal('-78.6589195')]
['Craig Braun', 53, '910 Sanchez Burg Suite 924', 'North Bryanfort', 'Minnesota', '53669', Decimal('57.514724'), Decimal('-45.8634655')]
['Christopher Harrington', 78, '861 Townsend Harbors Apt. 750', 'Lake Michaelberg', 'Montana', '61239', Decimal('166.765360'), Decimal('-28.683116')]
['Stephanie Morris', 19, '897 Rodriguez Crescent', 'South Danielstad', 'Vermont', '58175', Decimal('-51.749767'), Decimal('-42.028402')]
['Alison Williams', 64, '215 Delacruz Islands', 'Williamville', 'Alabama', '07273', Decimal('-88.169326'), Decimal('-36.705031')]
['Kevin Flynn', 27, '9706 Fernando Valleys', 'West Robertview', 'North Carolina', '29728', Decimal('-85.104753'), Decimal('-16.047558')]
['Dominic Johnson', 25, '1606 Christopher Bridge', 'Lake Adamfurt', 'Virginia', '55313', Decimal('-3.885144'), Decimal('31.3813855')]
['Rebekah Case', 20, '8558 Jeremy Stream', 'Lake Desireeshire', 'West Virginia', '72637', Decimal('-134.354548'), Decimal('-15.969008')]
['Wendy Jackson', 55, '63514 Sara Haven Suite 064', 'Rebeccamouth', 'Connecticut', '30662', Decimal('-68.206753'), Decimal('54.7347015')]
['Samantha Bradley', 63, '4588 John Locks Apt. 684', 'South Lindahaven', 'New Jersey', '70971', Decimal('121.554981'), Decimal('15.3405365')]
['Carolyn Mcgee', 70, '0634 Gwendolyn Walk Apt. 213', 'West Elizabeth', 'Michigan', '26238', Decimal('121.112186'), Decimal('89.935218')]
['Jennifer Holt', 67, '180 Bishop Knolls Suite 757', 'West Zacharyton', 'Hawaii', '87928', Decimal('-169.025022'), Decimal('71.4399035')]
['Nathan Jackson', 59, '534 Monica Trail Apt. 208', 'Port Jasonberg', 'Kentucky', '01160', Decimal('12.929182'), Decimal('-23.864826')]
['Leslie Ward', 38, '42452 Mccoy Inlet Apt. 968', 'Toddburgh', 'Illinois', '24762', Decimal('24.926569'), Decimal('-22.605383')]
['Carol Morales', 70, '8431 Nicholas Landing', 'New Jessica', 'South Dakota', '70658', Decimal('52.859992'), Decimal('-84.6671135')]
['Holly Allen', 19, '4217 Leonard Plaza Apt. 314', 'Debramouth', 'Texas', '68721', Decimal('125.842509'), Decimal('22.351546')]
['Jonathan Hamilton', 62, '11153 Andrew Extensions', 'East Nicole', 'Connecticut', '79402', Decimal('-152.005265'), Decimal('44.343711')]
['Wayne Jackson', 22, '4842 Susan Gardens Apt. 527', 'Trujilloville', 'Arkansas', '78813', Decimal('-108.172087'), Decimal('-30.0249095')]
['Hector Martinez', 27, '41296 Martin Island Suite 929', 'Davisview', 'Wyoming', '52209', Decimal('-124.794884'), Decimal('36.8193605')]
['Peter Ross', 48, '264 Joseph Squares Apt. 315', 'West Heathermouth', 'Florida', '62170', Decimal('-87.729679'), Decimal('31.8089675')]
['Kristen Hansen', 54, '20467 Eric Squares Apt. 714', 'Joseside', 'Massachusetts', '09290', Decimal('36.119926'), Decimal('-33.378574')]
['Maria Lee', 31, '881 Rosario Summit', 'Kimshire', 'Nebraska', '99865', Decimal('160.001129'), Decimal('86.744839')]
['Mrs. Kathleen Burgess', 69, '67072 Christina Mews', 'Maryberg', 'Rhode Island', '72507', Decimal('62.539280'), Decimal('60.052993')]
['Nathaniel Beltran', 36, '9027 Austin Keys', 'Cainshire', 'New Jersey', '53605', Decimal('16.938548'), Decimal('37.1164055')]
['Jason Stanley', 27, '38109 Carpenter Ranch Suite 031', 'Jacksonton', 'Delaware', '28747', Decimal('-168.557038'), Decimal('-24.218911')]
['Lawrence Jordan', 42, '5697 Gonzales Islands', 'Port Christina', 'California', '11100', Decimal('71.172465'), Decimal('71.872629')]
['Daniel Sweeney', 56, '136 Gilbert Ports Apt. 197', 'Nancyside', 'Wyoming', '55208', Decimal('85.907172'), Decimal('-35.4017925')]
['Aaron Cain', 77, '84342 Charles Unions Apt. 961', 'Cliffordville', 'Montana', '26426', Decimal('-173.887377'), Decimal('-23.5977065')]
['David Moss', 20, '5363 Denise Oval', 'East Stevenfort', 'Washington', '57877', Decimal('-166.101205'), Decimal('21.8580395')]
['Sara Vega', 58, '37573 Armstrong Fork Apt. 838', 'Robertshire', 'Mississippi', '67889', Decimal('28.244654'), Decimal('-52.7665405')]
['Steve Thornton', 52, '39201 Webb Lane', 'Walshville', 'Minnesota', '65300', Decimal('92.610217'), Decimal('-52.9831915')]
['Hayley Watts', 66, '4563 Miller Row', 'Kelseytown', 'South Carolina', '11391', Decimal('65.081309'), Decimal('-6.0756295')]
['Kimberly Brown', 21, '23589 Ritter Trafficway Suite 909', 'Lake Charles', 'Virginia', '99446', Decimal('115.045643'), Decimal('-63.370736')]
['Craig Rhodes', 60, '80000 Frank Crest', 'North Noahburgh', 'Georgia', '87286', Decimal('-159.356040'), Decimal('57.5919125')]
['Kyle Burke', 56, '91229 James Junctions', 'Mendozaborough', 'Hawaii', '20849', Decimal('-105.177421'), Decimal('-12.565899')]
['Wayne Hayes', 74, '055 Jennifer Harbor Suite 315', 'West Edwardton', 'New York', '70113', Decimal('149.982095'), Decimal('2.655506')]
['Mr. William Ryan', 66, '196 Gray Mountains Apt. 137', 'Laurenport', 'Iowa', '65541', Decimal('-46.933925'), Decimal('-38.349977')]
['Pamela Craig', 80, '375 Willie Mews', 'Lake Deborah', 'Colorado', '85324', Decimal('-80.960386'), Decimal('16.3131715')]
['Matthew Mcmillan', 70, '433 Yu Skyway', 'Jimenezstad', 'Rhode Island', '17568', Decimal('-168.816823'), Decimal('-32.148880')]
['Matthew Anderson', 66, '720 Donna Rapids', 'Lake Michaelland', 'Maryland', '04835', Decimal('61.487622'), Decimal('38.1248725')]